FROM node:22-alpine AS build
WORKDIR /app

COPY package*.json ./

RUN npm install --only=production --ignore-scripts

COPY src ./src

FROM node:22-alpine
WORKDIR /app

COPY --from=build /app/node_modules ./node_modules

COPY package*.json ./
COPY src ./src

RUN addgroup -g 1001 -S nodejs && \
    adduser -S nodejs -u 1001 && \
    chown -R nodejs:nodejs /app

USER nodejs

EXPOSE 3000

CMD ["node", "src/index.js"]