
services:
  limpora-server:
    networks:
      - limpora-network
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:Z
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=500
          
    depends_on:
      mysql:
        condition: service_healthy
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: limpora
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/dbscripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 5s
        timeout: 5s
        retries: 10
    networks:
      - limpora-network


volumes:
  mysql_data:
  node_modules:

networks:
  limpora-network:
    name: limpora-network
    driver: bridge