services:
  limpora-client:
    build:
      context: .
      dockerfile: ./limpora-client/Dockerfile.prod
    ports:
      - "127.0.0.1:3002:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - limpora-network

  limpora-server:
    build:
      context: .
      dockerfile: ./server/Dockerfile 
    ports:
      - "127.0.0.1:3001:3000"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
      - FRONTEND_URL=https://www.limpora.xyz
    volumes:
      - ./server/data:/usr/src/app/data
    restart: unless-stopped
    networks:
      - limpora-network

networks:
  limpora-network:
    name: limpora-network
    driver: bridge