services:
  limpora-client:
    build:
      context: .
      dockerfile: ./infra/docker/client.prod.Dockerfile
    ports:
      - "127.0.0.1:3002:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - limpora-network

  limpora-server:
    build:
      context: .
      dockerfile: ./infra/docker/server.prod.Dockerfile
    ports:
      - "127.0.0.1:3001:3000"
    env_file:
      - apps/server/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./apps/server/data:/usr/src/app/data
    restart: unless-stopped
    networks:
      - limpora-network

  loki:
    image: grafana/loki:latest
    ports:
      - "127.0.0.1:3100:3100"
    networks:
      - limpora-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      - limpora-network

networks:
  limpora-network:
    name: limpora-network
    driver: bridge