// ? MediaService
// ! ------------------------
// * Responsible for managing image requests.
// * Works as proxi/abstraction of Imagekit and has utility methods.
// * Third party alternatives: Cloudinary, google it, ask to a llm cus I'm in a rush.
// The above text wasn't generated by an IA. P.S. All doc headings like this one are written by me @Garkatron.

import { status } from "elysia";
import { ImageKitClient } from "../../libs/imagekit";
import { MediaModel } from "./model";
import { UserService } from "../user/service";

const ALLOWED_TYPES = ["image/jpeg", "image/png", "image/webp"];
const MAX_SIZE = 5 * 1024 * 1024; // 5MB

export abstract class MediaService {
    static async getImage({
        src,
    }: MediaModel["getImageBody"]): Promise<MediaModel["getImageResponse"]> {
        const url = ImageKitClient.helper.buildSrc({
            urlEndpoint: process.env.IMAGEKIT_URL_ENDPOINT!,
            src,
            // transformation: [],
        });
        return { url };
    }

    static async postImage({
        file,
        name,
        folder,
    }: MediaModel["postImageBody"]): Promise<MediaModel["postImageResponse"]> {
        if (!ALLOWED_TYPES.includes(file.type)) {
            throw status(
                400,
                `Invalid file type: ${file.type}. Allowed: ${ALLOWED_TYPES.join(", ")}`,
            );
        }

        if (file.size > MAX_SIZE) {
            throw status(
                400,
                `File too large: ${file.size} bytes. Max: ${MAX_SIZE}`,
            );
        }

        let response;

        try {
            response = await ImageKitClient.files.upload({
                fileName: name,
                folder,
                file,
                overwriteFile: true,
                useUniqueFileName: false,
            });
        } catch (err) {
            const message =
                err instanceof Error ? err.message : "Unknown error";
            throw status(502, `ImageKit upload failed: ${message}`);
        }

        if (!response.fileId || !response.url) {
            throw status(
                502,
                `ImageKit returned incomplete data: fileId=${response.fileId}, url=${response.url}`,
            );
        }

        return {
            id: response.fileId,
            public_url: response.url,
        };
    }

    static async setProfileImageMe(
        { file }: MediaModel["fileBody"],
        uid: string,
    ): Promise<MediaModel["postImageResponse"]> {
        const user = await UserService.getMe({ uid }); // Avoid not existent user.

        try {
            await ImageKitClient.files.delete(`user/${uid}/profile`);
        } catch (_) {
            // Ignore if not exists.
        }

        const response = await MediaService.postImage({
            file,
            name: `profile`,
            folder: `user/${uid}`,
        });

        return {
            public_url: response.public_url,
            id: response.id,
        };
    }
    static async getProfileImageMe(
        uid: string,
    ): Promise<MediaModel["getImageResponse"]> {
        await UserService.getMe({ uid }); // Avoid no existent user

        const response = await MediaService.getImage({
            src: `user/${uid}/profile`,
        });
        return {
            url: response.url,
        };
    }

    static async setBannerImageMe(
        { file }: MediaModel["fileBody"],
        uid: string,
    ): Promise<MediaModel["postImageResponse"]> {
        const user = await UserService.getMe({ uid }); // Avoid not existent user.

        try {
            await ImageKitClient.files.delete(`user/${uid}/banner`);
        } catch (_) {
            // Ignore if not exists.
        }

        const response = await MediaService.postImage({
            file,
            name: `banner`,
            folder: `user/${uid}`,
        });

        return {
            public_url: response.public_url,
            id: response.id,
        };
    }
    static async getBanerImageMe(
        uid: string,
    ): Promise<MediaModel["getImageResponse"]> {
        await UserService.getMe({ uid }); // Avoid no existent user

        const response = await MediaService.getImage({
            src: `user/${uid}/banner`,
        });
        return {
            url: response.url,
        };
    }
}
