// ? MediaService
// ! ------------------------
// * Responsible for managing image requests.
// * Works as proxi/abstraction of Imagekit and has utility methods.
// * Third party alternatives: Cloudinary, google it, ask to a llm cus I'm in a rush.
// The above text wasn't generated by an IA. P.S. All doc headings like this one are written by me @Garkatron.

import { status } from "elysia";
import { ImageKitClient } from "../../libs/imagekit";
import { MediaModel } from "./model";
import { UserService } from "../user/service";

const ALLOWED_TYPES = ["image/jpeg", "image/png", "image/webp"];
const MAX_SIZE = 5 * 1024 * 1024; // 5MB

export abstract class MediaService {
    static async getImage({
        src,
    }: MediaModel["getImageBody"]): Promise<MediaModel["getImageResponse"]> {
        const url = ImageKitClient.helper.buildSrc({
            urlEndpoint: process.env.IMAGEKIT_URL_ENDPOINT!,
            src,
            // transformation: [],
        });
        return { url };
    }

    static async postImage({
        file,
        name,
        folder,
    }: MediaModel["postImageBody"]): Promise<MediaModel["postImageResponse"]> {
        if (!ALLOWED_TYPES.includes(file.type)) {
            throw status(
                400,
                "Invalid file type. Allowed: image/jpeg, image/png, image/webp" satisfies MediaModel["invalidType"],
            );
        }

        if (file.size > MAX_SIZE) {
            throw status(
                400,
                "File too large. Max: 5242880 bytes" satisfies MediaModel["fileTooLarge"],
            );
        }

        let response;

        try {
            response = await ImageKitClient.files.upload({
                fileName: name,
                folder,
                file,
                overwriteFile: true,
                useUniqueFileName: false,
            });
        } catch (err) {
            const message =
                err instanceof Error ? err.message : "Unknown error";
            throw status(502, `Upload failed: ${message}` satisfies MediaModel["uploadFailed"]);
        }

        if (!response.fileId || !response.url) {
            throw status(
                502,
                `Incomplete data: fileId=${response.fileId}, url=${response.url}` satisfies MediaModel["incompleteResponse"],
            );
        }

        return {
            id: response.fileId,
            public_url: response.url,
        };
    }

    static async getProfileImage(
        { id }: MediaModel["profileParams"],
    ): Promise<MediaModel["getImageResponse"]> {
        return MediaService.getImage({ src: `user/${id}/profile` });
    }

    static async setProfileImage(
        { file }: MediaModel["fileBody"],
        id: number,
    ): Promise<MediaModel["postImageResponse"]> {
        try {
            await ImageKitClient.files.delete(`user/${id}/profile`);
        } catch (_) { }

        return MediaService.postImage({
            file,
            name: "profile",
            folder: `user/${id}`,
        });
    }

    static async getProfileImageMe(
        uid: string,
    ): Promise<MediaModel["getImageResponse"]> {
        const user = await UserService.getMe({ uid });
        return MediaService.getProfileImage({ id: user.id });
    }

    static async setProfileImageMe(
        { file }: MediaModel["fileBody"],
        uid: string,
    ): Promise<MediaModel["postImageResponse"]> {
        const user = await UserService.getMe({ uid });
        return MediaService.setProfileImage({ file }, user.id);
    }


    static async getBannerImage(
        { id }: MediaModel["bannerParams"],
    ): Promise<MediaModel["getImageResponse"]> {
        return MediaService.getImage({ src: `user/${id}/banner` });
    }

    static async setBannerImage(
        { file }: MediaModel["fileBody"],
        id: number,
    ): Promise<MediaModel["postImageResponse"]> {
        try {
            await ImageKitClient.files.delete(`user/${id}/banner`);
        } catch (_) { }

        return MediaService.postImage({
            file,
            name: "banner",
            folder: `user/${id}`,
        });
    }

    static async getBannerImageMe(
        uid: string,
    ): Promise<MediaModel["getImageResponse"]> {
        const user = await UserService.getMe({ uid });
        return MediaService.getBannerImage({ id: user.id });
    }

    static async setBannerImageMe(
        { file }: MediaModel["fileBody"],
        uid: string,
    ): Promise<MediaModel["postImageResponse"]> {
        const user = await UserService.getMe({ uid });
        return MediaService.setBannerImage({ file }, user.id);
    }
}
