FROM oven/bun:1 AS build

WORKDIR /app

COPY common/ /common/

COPY limpora-client/package.json limpora-client/bun.lock ./
RUN bun install --frozen-lockfile

COPY limpora-client/ .

RUN bun run build

FROM node:20-alpine

WORKDIR /app
RUN npm install -g serve
COPY --from=build /app/dist ./dist

EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]