FROM oven/bun:1-alpine AS build
WORKDIR /app

COPY package*.json ./
COPY bun.lockb* ./
RUN bun install

COPY . .
RUN bun run build

FROM oven/bun:1-alpine
WORKDIR /app

RUN bun install -g serve

COPY --from=build /app/dist ./dist

EXPOSE 3000

CMD ["serve", "-s", "dist", "-l", "3000"]