FROM oven/bun:1

WORKDIR /app

COPY common/ /common/

COPY limpora-client/package.json limpora-client/bun.lock ./
RUN bun install

COPY limpora-client/ .

EXPOSE 5173
CMD ["bun", "run", "dev", "--host"]