name: Deploy Develop 

on:
  push:
    branches:
      - develop

jobs:
  dev-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy repo to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 2222
          source: "./"
          target: "/var/www/html/ProyectoDaw2"

      - name: SSH and deploy Docker
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/html/ProyectoDaw2
            cat > limpora-server/.env <<EOF

            NODE_ENV=development
            API_PREFIX=${API_PREFIX}
            API_VERSION=${API_VERSION}
            PORT=${PORT}

            DB_NAME=${DB_NAME}
            DB_HOST=${DB_HOST}
            DB_PASS=${DB_PASS}
            DB_CONNECTION_LIMIT=${DB_CONNECTION_LIMIT}

            GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            FIREBASE_API_KEY=${FIREBASE_API_KEY}

            RESEND_KEY=${RESEND_KEY}
            RESEND_EMAIL_FROM=${RESEND_EMAIL_FROM}
            EOF

            # Deploy
            docker compose down
            docker compose pull
            docker compose up --build -d
        env:
            API_PREFIX: ${{ vars.API_PREFIX }}
            API_VERSION: ${{ vars.API_VERSION }}
            PORT: ${{ vars.PORT }}
            DB_NAME: ${{ vars.DB_NAME }}
            DB_HOST: ${{ secrets.DB_HOST }}
            DB_PASS: ${{ secrets.DB_PASS }}
            DB_CONNECTION_LIMIT: ${{ vars.DB_CONNECTION_LIMIT }}
            GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
            RESEND_KEY: ${{ secrets.RESEND_KEY }}
            RESEND_EMAIL_FROM: ${{ vars.RESEND_EMAIL_FROM }}